// SLF_FULL_MODEL_v1 - read API for the portal's SLF silo.
import { Router } from "express";
import { pool } from "../db/pool";
import { syncAllFamilies } from "../slf/sync.worker";
export function slfRouter() { const r = Router();
  r.get("/deals", async (req, res, next) => { try { const { stage, family, sub, q } = req.query as Record<string, string | undefined>; const limit = Math.min(Number(req.query.limit) || 100, 500); const offset = Number(req.query.offset) || 0; const where: string[] = ["r.hidden IS NOT TRUE"]; const p: unknown[] = []; if (stage) { p.push(stage); where.push(`r.stage = $${p.length}`); } if (family) { p.push(family); where.push(`r.product_family = $${p.length}`); } if (sub) { p.push(Number(sub)); where.push(`r.sub_id = $${p.length}`); } if (q) { p.push(`%${q}%`); where.push(`s.company_name ILIKE $${p.length}`); } p.push(limit); const lim = p.length; p.push(offset); const off = p.length; const { rows } = await pool.query(`SELECT r.id, r.product_family, r.amount, r.stage, r.notes, r.country, r.is_active, r.is_complete, r.offered, r.ongoing_loc_count, r.ongoing_loc_total, r.last_synced_at, s.id AS sub_id, s.company_name, s.city, s.province, s.sub_trade, s.is_approved, s.business_bankruptcy, s.personal_bankruptcy, u.first_name, u.last_name, u.email, u.phone_number, o.lender_name, o.status AS offer_status, o.amount AS offer_amount, o.original_interest_rate, o.interest_rate_type, o.reject_reason, (SELECT count(*) FROM slf_files f WHERE f.request_id = r.id) AS file_count, (SELECT count(*) FROM slf_contracts k WHERE k.request_id = r.id) AS contract_count FROM slf_requests r LEFT JOIN slf_subs s ON s.id = r.sub_id LEFT JOIN slf_users u ON u.id = s.applicant_user_id LEFT JOIN LATERAL (SELECT * FROM slf_offers o2 WHERE o2.request_id = r.id ORDER BY (o2.status = 'accepted') DESC, o2.slf_created_at DESC NULLS LAST LIMIT 1) o ON true WHERE ${where.join(" AND ")} ORDER BY r.last_synced_at DESC, r.id DESC LIMIT $${lim} OFFSET $${off}`, p); res.json({ success: true, data: rows }); } catch (e) { next(e); } });
  r.get("/deals/:id", async (req, res, next) => { try { const id = Number(req.params.id); const [reqRow, sub, contracts, offers, files] = await Promise.all([pool.query(`SELECT * FROM slf_requests WHERE id = $1`, [id]), pool.query(`SELECT s.*, a.email AS admin_email, a.first_name AS admin_first_name, a.last_name AS admin_last_name, a.phone_number AS admin_phone FROM slf_requests r JOIN slf_subs s ON s.id = r.sub_id LEFT JOIN slf_users a ON a.id = s.admin_user_id WHERE r.id = $1`, [id]), pool.query(`SELECT * FROM slf_contracts WHERE request_id = $1 ORDER BY id`, [id]), pool.query(`SELECT * FROM slf_offers WHERE request_id = $1 ORDER BY slf_created_at DESC NULLS LAST, id DESC`, [id]), pool.query(`SELECT * FROM slf_files WHERE request_id = $1 OR (owner_kind = 'sub' AND owner_id = (SELECT sub_id FROM slf_requests WHERE id = $1)) ORDER BY uploaded_at DESC NULLS LAST, id DESC`, [id])]); if (!reqRow.rows[0]) return res.status(404).json({ success: false, error: "not found" }); const users = sub.rows[0] ? (await pool.query(`SELECT * FROM slf_users WHERE sub_id = $1 ORDER BY id`, [sub.rows[0].id])).rows : []; const notes = [ ...(reqRow.rows[0].notes ? [{ source: "request", author: null, text: reqRow.rows[0].notes }] : []), ...(sub.rows[0]?.notes ? [{ source: "sub", author: sub.rows[0].company_name, text: sub.rows[0].notes }] : []), ...contracts.rows.filter((k) => k.notes).map((k) => ({ source: "contract", author: k.general_contractor, text: k.notes })), ...offers.rows.filter((o) => o.notes).map((o) => ({ source: "offer", author: o.lender_name, text: o.notes })), ...offers.rows.filter((o) => o.reject_reason).map((o) => ({ source: "offer_reject", author: o.lender_name, text: o.reject_reason })) ]; res.json({ success: true, data: { request: reqRow.rows[0], sub: sub.rows[0] ?? null, users, contracts: contracts.rows, offers: offers.rows, files: files.rows, notes } }); } catch (e) { next(e); } });
  r.get("/subs", async (_req, res, next) => { try { const { rows } = await pool.query(`SELECT s.*, count(r.id) AS request_count, coalesce(sum(r.amount),0) AS requested_total FROM slf_subs s LEFT JOIN slf_requests r ON r.sub_id = s.id GROUP BY s.id ORDER BY s.company_name`); res.json({ success: true, data: rows }); } catch (e) { next(e); } });
  r.get("/lenders", async (_req, res, next) => { try { const { rows } = await pool.query(`SELECT lender_id, lender_name, max(lender_logo) AS lender_logo, count(*) AS offer_count, count(*) FILTER (WHERE status = 'accepted') AS accepted_count, count(*) FILTER (WHERE reject_reason <> '') AS rejected_count, coalesce(sum(amount) FILTER (WHERE status = 'accepted'),0) AS accepted_total FROM slf_offers WHERE lender_id IS NOT NULL GROUP BY lender_id, lender_name ORDER BY lender_name`); res.json({ success: true, data: rows }); } catch (e) { next(e); } });
  r.get("/stats", async (_req, res, next) => { try { const [byStage, byFamily, sync] = await Promise.all([pool.query(`SELECT stage, count(*) AS n, coalesce(sum(amount),0) AS total FROM slf_requests WHERE hidden IS NOT TRUE GROUP BY stage`), pool.query(`SELECT product_family, count(*) AS n FROM slf_requests GROUP BY product_family`), pool.query(`SELECT * FROM slf_sync_runs ORDER BY started_at DESC LIMIT 10`)]); res.json({ success: true, data: { byStage: byStage.rows, byFamily: byFamily.rows, recentSyncs: sync.rows } }); } catch (e) { next(e); } });
  r.post("/sync", async (_req, res, next) => { try { await syncAllFamilies(true); res.json({ success: true }); } catch (e) { next(e); } }); return r; }
